version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb+srv://polgo:123456Ab@cluster0.6myv4ed.mongodb.net/
      JWT_SECRET: segredo_super_forte
      JWT_EXPIRES_IN: 1h
      ADMIN_USER: admin
      ADMIN_PASSWORD: 1234
      FRONTEND_URL: http://frontend:5173
    networks:
      - campanha-net
    restart: always
    command: npm run dev

  frontend:
    build:
      context: ../frontend/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    environment:
      VITE_API_URL: http://backend:8000
    networks:
      - campanha-net
    restart: always
    command: npm run dev -- --host 0.0.0.0

networks:
  campanha-net:
    driver: bridge
