# Etapa 1 - build da aplicação
FROM node:20 AS build
WORKDIR /app

# Copia pacotes e instala dependências
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Gera build de produção (Vite → dist/)
RUN npm run build

# Etapa 2 - nginx para servir os arquivos estáticos
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
